# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yr-sjwcAv9yr-eI_4yt5qIRsUC_Z5s5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df =pd.read_csv(r"/Sample - Superstore - Cleaned.csv")

from google.colab import drive
drive.mount('/content/drive')

df.head()

top_product=df.groupby('Product Name').head()

df.groupby('Product Name').head()