# -*- coding: utf-8 -*-
"""generated_sap_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Z4TQW3o67DuvvoQT8eGKyKvTnLF7w3H
"""

import os

if not os.path.exists('data'):
    os.makedirs('data')

# Save this as `generate_sap_data.py` and run it
import pandas as pd
from faker import Faker
fake = Faker()

def generate_sap_data(num_records=1000):
    data = {
        'equipment_id': [fake.uuid4()[:8] for _ in range(num_records)],
        'temperature': [fake.random_int(50, 150) for _ in range(num_records)],
        'vibration': [fake.random_int(1, 100) for _ in range(num_records)],
        'last_maintenance': [fake.date_this_year() for _ in range(num_records)]
    }
    return pd.DataFrame(data)

df = generate_sap_data()
df.to_csv('data/synthetic_sap.csv', index=False)